### ISSUE TITLE
NFC doesn't work.

### ISSUE THREAD

**Issue by davwheat** [quantify-nfc/Wear24-NFC-Kernel#7]
Quite simple, really.

It doesn't work.

**Comment by JaredTamana** [comment]
2/9/2019 -- driver is building into kernel, but no indication of PN54x in `/dev`. Need earlier dmesgs... some devices report registration at ~2s.

**Comment by velaar** [comment]
Will building as a module and trying to load it after the device boot help?

**Comment by davwheat** [comment]
Haven't thought about it. We could look into it.

**Comment by JaredTamana** [comment]
No. We have switched away from PN54x for the moment. We are now using the other NCI driver, which shows up properly.

**Comment by davwheat** [comment]
We could actually close this issue now I think about it.
